### PR TITLE
Issue 22b

### PR DESCRIPTION
**Pull request by rufoa**
extra changes while we're here @fzakaria

### CODE REVIEW

**Comment by fzakaria** [comment]
@rufoa cool. feel free to self-approve any future ones.
I've been out of the clojure game for a bit :)

I just released the previous change so ill sit on these for deploy until next issue ?

**Comment by rufoa** [comment]
the third commit in this PR was a bugfix I'm afraid, so we'll need to bump the version again if you've already published a jar (sorry)

it's ready to go so please pull from master and redeploy to clojars

**Comment by rufoa** [comment]
actually could you just add me to the clojars group (username: rufo) https://clojars.org/groups/slf4j-timbre

**Comment by fzakaria** [comment]
@rufoa added `rufo`
Let me know if you have trouble deploying

**Comment by rufoa** [comment]
works great. thanks

**Pull request merged**
