### PR TITLE
moved slf4j to dependencies

### PR DESCRIPTION
**Pull request by fzakaria**
@rufoa review

### CODE REVIEW

**Comment by rufoa** [comment]
beat me to it!

**Comment by fzakaria** [comment]
@rufoa  i pushed to clojars https://clojars.org/com.fzakaria/slf4j-timbre/versions/0.3.0
but I don't see the ability to promote :o:

**Comment by rufoa** [comment]
hrm, looks like they got rid of it (I never actually used it myself)
https://github.com/clojars/clojars-web/issues/415

**Comment by fzakaria** [comment]
good find.

Farid Zakaria

**Pull request closed without merging**
