### PR TITLE
Add missing function

### PR DESCRIPTION
**Pull request by rufoa**
Thanks for making this library - it's very useful!

I've added a function which was missing. Could you push a new build to clojars please?

### CODE REVIEW

**Comment by fzakaria** [comment]
I'm in bed at the moment but first thing in the morning.

**Comment by rufoa** [comment]
Thanks! (fixes #2)
Could you push it to clojars too please

**Comment by fzakaria** [comment]
Pushed to clojars

**Comment by fzakaria** [comment]
Thanks @rufo for the fix.
I added some more "tests" that just call every log level.

Ideally, I'd like to figure out a way to have Timbre write to a ByteArrayOutputStream and then run some proper tests there. My clojurefu is still new so I will give it a go on the weekend (or contributions welcome!)

**Pull request merged**
